POST http://localhost:3333/event
Content-Type: application/json

{
  "title": "Node Sumit",
  "details": null,
  "maximumAttendees": 2
}

###

POST http://localhost:3333/event/dfb18d23-c2c4-433d-83dc-8147c454584d/attendee
Content-Type: application/json

{
  "name": "Joe",
  "email": "joe@gmail.com"
}

###
GET http://localhost:3333/events/dfb18d23-c2c4-433d-83dc-8147c454584d

###
GET http://localhost:3333/attendees/4/badge

###
GET http://localhost:3333/attendees/5/check-in

###
GET http://localhost:3333/events/dfb18d23-c2c4-433d-83dc-8147c454584d/attendees
